# config for analysis
aggregate_fract_infect_csvs: results/neut_titers/fracinfect.csv

rbd_depletions_date: 2021-06-10

elisa_data_dir: data/rbd_depletion_elisas
final_depletion_elisas: data/rbd_depletion_elisas/210513_ELISA_3xdep.csv

haarvi_rbd_depletions: data/haarvi_rbd_depletion_foldchange_ic50.csv

fixtop: True
fixbottom: 0

serum_order:
  - K007
  - K031
  - K033
  - K040
  - K041
  - K046
  - K114
  - K115
  - K119
  - K116
  - K006
  - participant A (day 21)
  - participant B (day 26)
  - participant C (day 32)
  - participant I (day 26)
  - participant A (day 120)
  - participant B (day 113)
  - participant C (day 104)
  - participant E (day 104)
  - participant G (day 94)
  - participant I (day 102)
  - REGN10987 (spike-in)
  - pre-pandemic

rename_sera:
  23_d21: participant A (day 21)
  24C_d32: participant C (day 32)
  23C_d26: participant I (day 26)
  1C_d26: participant B (day 26)
  24C_d104: participant C (day 104)
  22C_d104: participant E (day 104)
  23C_d102: participant I (day 102)
  1C_d113: participant B (day 113)
  23_d120: participant A (day 120)
  25_d94: participant G (day 94)

sera_for_further_analysis:
  - K007
  - K031
  - K033
  - K040
  - K041
  - K046
  - K114
  - K119
  - participant A (day 21)
  - participant B (day 26)
  - participant C (day 32)
  - participant I (day 26)
  - participant A (day 120)
  - participant B (day 113)
  - participant C (day 104)
  - participant E (day 104)
  - participant G (day 94)
  - participant I (day 102)

infecting_virus:
  K007: B.1.351
  K031: B.1.351
  K033: B.1.351
  K040: B.1.351
  K041: B.1.351
  K046: B.1.351
  K114: B.1.351
  K119: B.1.351
  participant A (day 21): early 2020
  participant B (day 26): early 2020
  participant C (day 32): early 2020
  participant I (day 26): early 2020
  participant A (day 120): early 2020 (100d)
  participant B (day 113): early 2020 (100d)
  participant C (day 104): early 2020 (100d)
  participant E (day 104): early 2020 (100d)
  participant G (day 94): early 2020 (100d)
  participant I (day 102): early 2020 (100d)

virus_order:
  - wildtype
  - B.1.351
  - mock
  - B.1.351-N417K
  - B.1.351-K484E
  - B.1.351-K484Q
  - B.1.351-L452R
  - B.1.351-G446V
  - B.1.351-K444E
  - B.1.351-Y501N
  - B.1.351-N417K-K484E-Y501N
  - K417N
  - E484K
  - E484Q
  - L452R
  - N501Y
  - G446V
  - K417N-E484K-N501Y
  - RBD antibodies depleted

virus_simplified_names:
  wildtype: wildtype
  B.1.351: wildtype
  mock: wildtype
  B.1.351-N417K: 417K/N
  B.1.351-K484E: 484E/K
  B.1.351-K484Q: 484Q
  B.1.351-L452R: L452R
  B.1.351-G446V: G446V
  B.1.351-K444E: K444E
  B.1.351-Y501N: 501N/Y
  B.1.351-N417K-K484E-Y501N: '417-484-501'
  K417N: 417K/N
  E484K: 484E/K
  E484Q: 484Q
  L452R: L452R
  N501Y: 501N/Y
  G446V: G446V
  K417N-E484K-N501Y: '417-484-501'
  RBD antibodies depleted: 'RBD antibodies depleted'

virus_simplified_names_order:
  - wildtype
  - L452R
  - G446V
  - 417K/N
  - 501N/Y
  - 484E/K
  - 484Q
  - 417-484-501
  - RBD antibodies depleted

virus_subsets:
  all:
    - wildtype
    - B.1.351-N417K
    - B.1.351-K484E
    - B.1.351-K484Q
    - B.1.351-L452R
    - B.1.351-G446V
    - B.1.351-Y501N
    - B.1.351-N417K-K484E-Y501N
    - K417N
    - E484K
    - E484Q
    - L452R
    - N501Y
    - G446V
    - K417N-E484K-N501Y
    - RBD antibodies depleted

# enter all the samples and stuff to ignore here
neut_samples_ignore:
  2021-08-20: [B.1.351-K484Q] # these were repeated on 2021-08-27
  2021-08-21: [B.1.351-K484Q] # these were repeated on 2021-08-27
  2021-03-08: [E484K]         # these were repeated on 2021-03-12

# the neutralization limit of detection is equal to the starting dilution
NT50_LOD: 25
